schema_version: 1

context:
  name: atlas-mc-scanner
  version: "1.0.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/atlas_mc_scanner-${{ version }}.tar.gz
  sha256: 9edb7a0d6cb74d94ac653f93ca1447c5af068fc6c3698f08f10324ba9c7f7938

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - atlas-mc-scanner = atlas_mc_scanner.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - typer >=0.9.0
    - func_adl_servicex_xaodr25
    - awkward
    - servicex-analysis-utils
    - tabulate
    - particle
    - jinja2

tests:
  - python:
      imports:
        - atlas_mc_scanner
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip list
      - atlas-mc-scanner --help

about:
  summary: ServiceX command line tools for inspecting ATLAS Monte Carlo datasets
  homepage: https://github.com/gordonwatts/atlas-mc-scanner
  license: MIT
  license_file: LICENSE.txt
  repository: https://github.com/gordonwatts/atlas-mc-scanner

extra:
  recipe-maintainers:
    - matthewfeickert
